export const category = [
  'Books and Literature',
  'Business and Finance',
  'Education',
  'Entertainment',
  'Food and Cooking',
  'Gaming',
  'Home Improvement',
  'Lifestyle',
  'Nature',
  'Parenting',
  'Personal Development',
  'Science',
  'Social Issues',
  'Sports and Fitness',
  'Technology',
  'Travel',
];
